# Generated by Django 2.2.10 on 2021-03-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timeseries_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100, verbose_name='参数信息')),
                ('arima_score', models.FloatField(verbose_name='自回归分数')),
                ('arima_img', models.CharField(max_length=100, verbose_name='自回归图片地址')),
                ('mfarima_score', models.FloatField(verbose_name='平滑滤波+自回归分数')),
                ('mfarima_img', models.CharField(max_length=100, verbose_name='平滑滤波+自回归图片地址')),
                ('waarima_score', models.FloatField(verbose_name='小波分析+自回归分数')),
                ('waarima_img', models.CharField(max_length=100, verbose_name='小波分析+自回归图片地址')),
                ('predict_name', models.CharField(max_length=100, verbose_name='最优预测算法名称')),
                ('predict_score', models.FloatField(verbose_name='最优预测算法分数')),
                ('predict_img', models.CharField(max_length=100, verbose_name='最优预测算法图片地址')),
            ],
            options={
                'verbose_name': '时间序列',
                'verbose_name_plural': '时间序列',
            },
        ),
    ]
