# Generated by Django 2.2.10 on 2021-03-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='decisiontree_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100, verbose_name='参数信息')),
                ('dt_score', models.FloatField(verbose_name='二元决策树分数')),
                ('dt_img', models.CharField(max_length=100, verbose_name='二元决策树图片地址')),
                ('rf_score', models.FloatField(verbose_name='随机森林分数')),
                ('rf_img', models.CharField(max_length=100, verbose_name='随机森林图片地址')),
                ('gb_score', models.FloatField(verbose_name='梯度提升树分数')),
                ('gb_img', models.CharField(max_length=100, verbose_name='梯度提升树图片地址')),
                ('ada_score', models.FloatField(verbose_name='自适应增强树分数')),
                ('ada_img', models.CharField(max_length=100, verbose_name='自适应增强树图片地址')),
                ('predict_name', models.CharField(max_length=100, verbose_name='最优预测算法名称')),
                ('predict_score', models.FloatField(verbose_name='最优预测算法分数')),
                ('predict_img', models.CharField(max_length=100, verbose_name='最优预测算法图片地址')),
            ],
            options={
                'verbose_name': '决策树',
                'verbose_name_plural': '决策树',
            },
        ),
    ]
