# Generated by Django 2.2.10 on 2021-02-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recommendation_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=5000, verbose_name='推荐数据')),
                ('item', models.IntegerField(max_length=500, verbose_name='条目')),
            ],
            options={
                'verbose_name': '推荐数据',
                'verbose_name_plural': '推荐数据',
            },
        ),
    ]
