# Generated by Django 2.2.10 on 2021-02-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem', '0002_auto_20210202_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation_data',
            name='data',
            field=models.CharField(max_length=50000, verbose_name='推荐数据'),
        ),
        migrations.AlterField(
            model_name='recommendation_data',
            name='item',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='条目'),
        ),
    ]
