# Generated by Django 2.2.10 on 2021-02-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem', '0003_auto_20210202_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation_data',
            name='data',
            field=models.CharField(max_length=1000000, verbose_name='推荐数据'),
        ),
    ]
